// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitanFitness.Infrastructure.DataContext;

#nullable disable

namespace TitanFitness.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TitanFitness.Domain.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time")
                        .HasColumnName("ClosingTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time")
                        .HasColumnName("OpeningTime");

                    b.HasKey("Id");

                    b.ToTable("Branches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Branches_ClosingTime_After_OpeningTime", "[ClosingTime] > [OpeningTime]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            Name = "Amman Main Branch",
                            OpeningTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClosingTime = new TimeOnly(23, 0, 0),
                            Name = "Khalda Branch",
                            OpeningTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            ClosingTime = new TimeOnly(22, 0, 0),
                            Name = "Abdoun Branch",
                            OpeningTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            ClosingTime = new TimeOnly(22, 30, 0),
                            Name = "Sweifieh Branch",
                            OpeningTime = new TimeOnly(6, 30, 0)
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Branches.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Studios_Branches");

                    b.ToTable("Studios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Studios_Capacity_Positive", "[Capacity] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Capacity = 20,
                            Name = "Studio A"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Capacity = 15,
                            Name = "Zen Room"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Capacity = 25,
                            Name = "Cycle Studio"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Capacity = 20,
                            Name = "Studio A"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            Capacity = 18,
                            Name = "Strength Studio"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Capacity = 25,
                            Name = "Cycle Studio"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 3,
                            Capacity = 15,
                            Name = "Yoga Studio"
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 3,
                            Capacity = 20,
                            Name = "Studio B"
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 3,
                            Capacity = 16,
                            Name = "Functional Studio"
                        },
                        new
                        {
                            Id = 10,
                            BranchId = 4,
                            Capacity = 20,
                            Name = "Studio A"
                        },
                        new
                        {
                            Id = 11,
                            BranchId = 4,
                            Capacity = 15,
                            Name = "Zen Room"
                        },
                        new
                        {
                            Id = 12,
                            BranchId = 4,
                            Capacity = 25,
                            Name = "Cycle Studio"
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.CheckIns.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CheckInId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("CheckInResult")
                        .HasColumnType("int")
                        .HasColumnName("Result");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateTime");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RefusalReason");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_CheckIns_Branches");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_CheckIns_Members");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("TitanFitness.Domain.ClassSessions.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("BookedOn");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("SessionId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("TrainerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TrainerNotes");

                    b.Property<int?>("WaitlistPosition")
                        .HasColumnType("int")
                        .HasColumnName("WaitlistPosition");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_Bookings_Members");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_Bookings_ClassSessions");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_WaitlistPosition_Positive", "[WaitlistPosition] IS NULL OR [WaitlistPosition] > 0");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.ClassSessions.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SessionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("int")
                        .HasColumnName("CapacityLimit");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ClassName");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DurationMinutes");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("SessionDate");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("StartTime");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("StudioId")
                        .HasColumnType("int")
                        .HasColumnName("StudioId");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int")
                        .HasColumnName("TrainerId");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_ClassSessions_Branches");

                    b.HasIndex("StudioId")
                        .HasDatabaseName("IX_ClassSessions_Studios");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("IX_ClassSessions_Trainers");

                    b.ToTable("ClassSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClassSessions_CapacityLimit_Positive", "[CapacityLimit] > 0");

                            t.HasCheckConstraint("CK_ClassSessions_DurationMinutes_Allowed", "[DurationMinutes] IN (30, 45, 60)");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FullName");

                    b.Property<int>("HomeBranchId")
                        .HasColumnType("int")
                        .HasColumnName("HomeBranchId");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date")
                        .HasColumnName("JoinedDate");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Photo");

                    b.HasKey("Id");

                    b.HasIndex("HomeBranchId")
                        .HasDatabaseName("IX_Members_Branches");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.Freeze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FreezeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int")
                        .HasColumnName("DurationInMonths");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("MembershipId");

                    b.Property<int>("Reason")
                        .HasColumnType("int")
                        .HasColumnName("Reason");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("RequestedOn");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_Freezes_Memberships");

                    b.ToTable("Freezes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Freezes_DurationInMonths_Positive", "[DurationInMonths] > 0");

                            t.HasCheckConstraint("CK_Freezes_EndDate_AfterOrEqual_StartDate", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.GuestPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuestPassId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GuestName");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("IssuedOn");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("MembershipId");

                    b.Property<DateOnly?>("UsedOn")
                        .HasColumnType("date")
                        .HasColumnName("UsedOn");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_GuestPasses_Memberships");

                    b.ToTable("GuestPasses", null, t =>
                        {
                            t.HasCheckConstraint("CK_GuestPasses_UsedOn_AfterOrEqual_IssuedOn", "[UsedOn] IS NULL OR [UsedOn] >= [IssuedOn]");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MembershipId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanId");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PurchaseDate");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_Memberships_Members");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_Memberships_Plans");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Memberships_EndDate_After_StartDate", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Plans.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessScope")
                        .HasColumnType("int")
                        .HasColumnName("AccessScope");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int")
                        .HasColumnName("DurationInMonths");

                    b.Property<int>("GuestPassQuota")
                        .HasColumnType("int")
                        .HasColumnName("GuestPassQuota");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("IsPublished");

                    b.Property<int>("MaxFreezeDays")
                        .HasColumnType("int")
                        .HasColumnName("MaxFreezeDays");

                    b.Property<int>("MaxFreezes")
                        .HasColumnType("int")
                        .HasColumnName("MaxFreezes");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PlanName");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Plans_DurationInMonths_Positive", "[DurationInMonths] > 0");

                            t.HasCheckConstraint("CK_Plans_GuestPassQuota_NonNegative", "[GuestPassQuota] >= 0");

                            t.HasCheckConstraint("CK_Plans_MaxFreezeDays_NonNegative", "[MaxFreezeDays] >= 0");

                            t.HasCheckConstraint("CK_Plans_MaxFreezes_NonNegative", "[MaxFreezes] >= 0");

                            t.HasCheckConstraint("CK_Plans_Price_NonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("TitanFitness.Domain.Trainers.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrainerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specialty");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Trainers_Branches");

                    b.ToTable("Trainers", (string)null);
                });

            modelBuilder.Entity("TitanFitness.Domain.Branches.Branch", b =>
                {
                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TitanFitness.Domain.Branches.Studio", b =>
                {
                    b.HasOne("TitanFitness.Domain.Branches.Branch", null)
                        .WithMany("Studios")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Studios_Branches_BranchId");
                });

            modelBuilder.Entity("TitanFitness.Domain.CheckIns.CheckIn", b =>
                {
                    b.HasOne("TitanFitness.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CheckIns_Branches_BranchId");

                    b.HasOne("TitanFitness.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CheckIns_Members_MemberId");
                });

            modelBuilder.Entity("TitanFitness.Domain.ClassSessions.Booking", b =>
                {
                    b.HasOne("TitanFitness.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Members_MemberId");

                    b.HasOne("TitanFitness.Domain.ClassSessions.ClassSession", null)
                        .WithMany("Bookings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_ClassSessions_SessionId");
                });

            modelBuilder.Entity("TitanFitness.Domain.ClassSessions.ClassSession", b =>
                {
                    b.HasOne("TitanFitness.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClassSessions_Branches_BranchId");

                    b.HasOne("TitanFitness.Domain.Branches.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClassSessions_Studios_StudioId");

                    b.HasOne("TitanFitness.Domain.Trainers.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClassSessions_Trainers_TrainerId");
                });

            modelBuilder.Entity("TitanFitness.Domain.Members.Member", b =>
                {
                    b.HasOne("TitanFitness.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("HomeBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Members_Branches_HomeBranchId");

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.MembershipNumber", "MembershipNumber", b1 =>
                        {
                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MembershipNumber");

                            b1.HasKey("MemberId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Members_MembershipNumber");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("MemberId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Email");

                    b.Navigation("MembershipNumber")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.Freeze", b =>
                {
                    b.HasOne("TitanFitness.Domain.Memberships.Membership", null)
                        .WithMany("Freezes")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Freezes_Memberships_MembershipId");
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.GuestPass", b =>
                {
                    b.HasOne("TitanFitness.Domain.Memberships.Membership", null)
                        .WithMany("GuestPasses")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GuestPasses_Memberships_MembershipId");
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.Membership", b =>
                {
                    b.HasOne("TitanFitness.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_Members_MemberId");

                    b.HasOne("TitanFitness.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_Plans_PlanId");

                    b.OwnsOne("TitanFitness.Domain.Memberships.AgreedTerms", "AgreedTerms", b1 =>
                        {
                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<int>("AccessScope")
                                .HasColumnType("int")
                                .HasColumnName("AccessScope");

                            b1.Property<int>("DurationInMonths")
                                .HasColumnType("int")
                                .HasColumnName("DurationInMonths");

                            b1.Property<int>("GuestPassQuota")
                                .HasColumnType("int")
                                .HasColumnName("GuestPassQuota");

                            b1.Property<int>("MaxFreezeDays")
                                .HasColumnType("int")
                                .HasColumnName("MaxFreezeDays");

                            b1.Property<int>("MaxFreezes")
                                .HasColumnType("int")
                                .HasColumnName("MaxFreezes");

                            b1.Property<decimal>("PricePaid")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PricePaid");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("AgreedTerms")
                        .IsRequired();
                });

            modelBuilder.Entity("TitanFitness.Domain.Trainers.Trainer", b =>
                {
                    b.HasOne("TitanFitness.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Trainers_Branches_BranchId");

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.OwnsOne("TitanFitness.Domain.Common.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("TitanFitness.Domain.Branches.Branch", b =>
                {
                    b.Navigation("Studios");
                });

            modelBuilder.Entity("TitanFitness.Domain.ClassSessions.ClassSession", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TitanFitness.Domain.Memberships.Membership", b =>
                {
                    b.Navigation("Freezes");

                    b.Navigation("GuestPasses");
                });
#pragma warning restore 612, 618
        }
    }
}
